table Date
	lineageTag: 860ca4ae-208d-450d-9974-9873d633bf7e

	column 'Date Id'
		dataType: string
		lineageTag: c6c9dbee-a1d9-492b-bbf2-3115bba7f1af
		summarizeBy: none
		sourceColumn: Date Id

		annotation SummarizationSetBy = Automatic

	column Date
		dataType: dateTime
		formatString: Short Date
		lineageTag: 040777d7-79c8-484e-a0e4-68a2c6dc742b
		summarizeBy: none
		sourceColumn: Date

		variation Variation
			isDefault
			relationship: 5296e5c9-4771-42b0-9fb5-ed344669c117
			defaultHierarchy: LocalDateTable_039f8286-f633-4191-b80c-96f312fccd90.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column Year
		dataType: int64
		lineageTag: 9fdff8be-ab85-4281-8d16-dc8466a7e60d
		summarizeBy: none
		sourceColumn: Year

		changedProperty = DataType

		annotation SummarizationSetBy = User

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Month
		dataType: int64
		lineageTag: 8782bd2e-6e7e-4e0c-9e74-d63f08bebba2
		summarizeBy: none
		sourceColumn: Month

		changedProperty = DataType

		annotation SummarizationSetBy = User

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Month Name'
		dataType: string
		lineageTag: 6d3b2613-e1c2-46ba-81a8-f422e7738b4b
		summarizeBy: none
		sourceColumn: Month Name
		sortByColumn: Month

		changedProperty = SortByColumn

		annotation SummarizationSetBy = Automatic

	column Quarter
		dataType: double
		lineageTag: 103fa737-2e76-49b1-9bc3-c82ad4b9d734
		summarizeBy: none
		sourceColumn: Quarter

		annotation SummarizationSetBy = User

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Week of Year'
		dataType: double
		formatString: 0
		lineageTag: 168eb73e-ed78-4321-8d8a-b95c09bc223c
		summarizeBy: none
		sourceColumn: Week of Year

		annotation SummarizationSetBy = User

	column 'Week of Month'
		dataType: double
		lineageTag: f3260b35-9815-473c-abb1-8553015fc006
		summarizeBy: none
		sourceColumn: Week of Month

		annotation SummarizationSetBy = User

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Day
		dataType: double
		lineageTag: e8e0f2fb-0880-4c56-9e9f-dc0ca6633255
		summarizeBy: none
		sourceColumn: Day

		annotation SummarizationSetBy = User

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Day of Week'
		dataType: double
		lineageTag: 3fb0eef0-b053-409b-bca9-0f361fa4215e
		summarizeBy: none
		sourceColumn: Day of Week

		annotation SummarizationSetBy = User

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Day of Year'
		dataType: double
		lineageTag: 7b995f20-18e7-4232-99c4-97b5925dfa31
		summarizeBy: none
		sourceColumn: Day of Year

		annotation SummarizationSetBy = User

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Day Name'
		dataType: string
		lineageTag: 969e2b1a-25a4-4cfc-b037-49c68d939150
		summarizeBy: none
		sourceColumn: Day Name
		sortByColumn: 'Day of Week'

		changedProperty = SortByColumn

		annotation SummarizationSetBy = Automatic

	column 'Is Month to Date'
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: e75f3407-f4d0-4db3-96cd-86433fbd0490
		summarizeBy: none
		sourceColumn: Is Month to Date

		annotation SummarizationSetBy = Automatic

	column 'Day Short Name'
		dataType: string
		lineageTag: e3127b6a-bff4-4580-8fc7-268b173ef0cd
		summarizeBy: none
		sourceColumn: Day Short Name
		sortByColumn: 'Day of Week'

		changedProperty = SortByColumn

		annotation SummarizationSetBy = Automatic

	column 'Month Short Name'
		dataType: string
		lineageTag: 789978fa-1b39-45e2-b0f7-323faa71576c
		summarizeBy: none
		sourceColumn: Month Short Name
		sortByColumn: Month

		changedProperty = SortByColumn

		annotation SummarizationSetBy = Automatic

	column 'Year-Month Number'
		dataType: string
		lineageTag: 5925c845-26bd-458b-bf66-53d8ee6fcc9d
		summarizeBy: none
		sourceColumn: Year-Month Number

		annotation SummarizationSetBy = Automatic

	column Year-Mth
		dataType: string
		lineageTag: 8b719b0b-7bd3-4e6a-b50e-a6c65ce0c6c8
		summarizeBy: none
		sourceColumn: Year-Mth
		sortByColumn: 'Year-Month Number'

		changedProperty = SortByColumn

		annotation SummarizationSetBy = Automatic

	column Year-Quarter
		dataType: string
		lineageTag: a3eadbb3-5400-4c05-b6da-2ae00e2a4539
		summarizeBy: none
		sourceColumn: Year-Quarter

		annotation SummarizationSetBy = Automatic

	column Quarter-Year
		dataType: string
		lineageTag: 3336b1dd-d584-4abf-b19b-fceeddef4831
		summarizeBy: none
		sourceColumn: Quarter-Year

		annotation SummarizationSetBy = Automatic

	column 'Is Weekend'
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: 2732e649-3b1a-4a8d-9a26-3f8e65fed55c
		summarizeBy: none
		sourceColumn: Is Weekend

		annotation SummarizationSetBy = Automatic

	column 'Is Current Month'
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: 567bdd7f-2b25-4ec4-aa96-a5fe790bfd80
		summarizeBy: none
		sourceColumn: Is Current Month

		annotation SummarizationSetBy = Automatic

	column 'Is Current Quarter'
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: fa057510-fd09-46d3-8070-031479818551
		summarizeBy: none
		sourceColumn: Is Current Quarter

		annotation SummarizationSetBy = Automatic

	column 'Is ETC to Date' = 'Date'[Date] > [Estimated to Complete As Of Date] && 'Date'[Date] <= [Hours Refreshed Thru]
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: 78b0def4-684b-4571-9d1a-cd851ab7224c
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column 'Is Refresh Date'
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: e70448b4-fd27-4259-9f62-9f06facf9946
		summarizeBy: none
		sourceColumn: Is Refresh Date

		annotation SummarizationSetBy = Automatic

	column 'Is Future Date'
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: f542e060-5302-45f0-90b1-f63243cecbd2
		summarizeBy: none
		sourceColumn: Is Future Date

		annotation SummarizationSetBy = Automatic

	column 'Is Month to Date Selector' =
			
			switch(
			    true,
			    'Date'[Is Month to Date] = true, "Month to Date",
			    'Date'[Is Month to Date] = false, "Not Month to Date"
			)
		lineageTag: 8782fb99-1f46-4202-b47f-6179f094ab07
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column 'Is ETC to Date Selector' =
			
			switch(
			    true,
			    'Date'[Is ETC to Date] = true, "ETC to Date",
			    'Date'[Is ETC to Date] = false, "Not ETC to Date"
			)
		lineageTag: f22d56b1-c3fd-4ad0-9824-edb776b880f9
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column 'Week Start Date'
		dataType: dateTime
		formatString: Long Date
		lineageTag: 4949355b-8a8f-46e0-82d7-9385068d62cd
		summarizeBy: none
		sourceColumn: Week Start Date

		variation Variation
			isDefault
			relationship: fcde15f8-0656-4fb2-8895-f2cf817c5166
			defaultHierarchy: LocalDateTable_5c792a5b-246a-4641-9869-c1e1c885e3b6.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column 'Week End Date'
		dataType: dateTime
		formatString: Long Date
		lineageTag: de944137-caa2-4aca-8adb-41bb748c4591
		summarizeBy: none
		sourceColumn: Week End Date

		variation Variation
			isDefault
			relationship: b3edf415-5cf6-4047-91f4-e74dc007c50a
			defaultHierarchy: LocalDateTable_10ce33fe-dc94-4d3c-b9ae-6d31269de0e3.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column 'Calendar Week Start Date'
		dataType: dateTime
		formatString: Short Date
		lineageTag: b41a3e6c-a406-4bd6-8d99-877f067df9fd
		summarizeBy: none
		sourceColumn: Calendar Week Start Date

		variation Variation
			isDefault
			relationship: 94c66339-81bc-4a01-8e59-2f3fa277a812
			defaultHierarchy: LocalDateTable_ff90c369-3971-466a-85ea-ee17e91c05a9.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column 'Year Month Id'
		dataType: double
		formatString: 0
		lineageTag: 5f83ec98-4c76-4164-b2ea-fe38ded64757
		summarizeBy: none
		sourceColumn: Year Month Id

		annotation SummarizationSetBy = User

	column 'Is Before Current Month'
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: 86596ed2-7d55-4ee5-84d6-260869adf25e
		summarizeBy: none
		sourceColumn: Is Before Current Month

		annotation SummarizationSetBy = Automatic

	column 'Is Before Current Month Selector' =
			
			switch(
			    true,
			    'Date'[Is Before Current Month] = true, "Exclude Current Month",
			    'Date'[Is Before Current Month] = false, "Include Current Month"
			)
		lineageTag: 6b96b88b-f1ad-45dc-8816-fe49ad5e977b
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column 'Day Index'
		dataType: double
		formatString: 0
		lineageTag: 37aacdcd-6d4d-4b66-91ed-883a8d5a160d
		summarizeBy: none
		sourceColumn: Day Index

		annotation SummarizationSetBy = User

	column 'Month Index'
		dataType: double
		formatString: 0
		lineageTag: 1d30726e-e6df-4626-900f-5d8caadb7afd
		summarizeBy: none
		sourceColumn: Month Index

		annotation SummarizationSetBy = User

	column 'Quarter Index'
		dataType: double
		formatString: 0
		lineageTag: e47ef622-8aa6-47ab-ae71-8693464465f6
		summarizeBy: none
		sourceColumn: Quarter Index

		annotation SummarizationSetBy = User

	column 'Week Index'
		dataType: double
		formatString: 0
		lineageTag: b9363e31-2f1f-4158-b7da-6e2a5d8f420e
		summarizeBy: none
		sourceColumn: Week Index

		annotation SummarizationSetBy = User

	partition Date = m
		mode: import
		queryGroup: Dimensions
		source = ```
				let
				    // Reference to Hours Actual table to get the max and min Date Id
				    MaxDateId = Text.From(List.Max(Table.Column(#"Hours Actual", "Date Id"))),
				    MinDateId = Text.From("20241001"),
				    
				    // Format the strings for conversion to dates
				    MaxFormattedDateString = Text.Insert(Text.Insert(MaxDateId, 4, "-"), 7, "-"),
				    MinFormattedDateString = Text.Insert(Text.Insert(MinDateId, 4, "-"), 7, "-"),
				    
				    // Get Refresh Thru Date upfront for use throughout the query
				    #"Get Refresh Thru Date" = #"Meta"{0}[Hours Refreshed Thru],
				    
				    // Applied Steps
				    StartDate = Date.FromText(MinFormattedDateString),
				    EndDate = Date.FromText(MaxFormattedDateString),
				    CurrentDate = #"Get Refresh Thru Date", // Changed from DateTime.LocalNow()
				    NumberOfDays = Duration.Days( EndDate - StartDate ),
				    Dates = List.Dates(StartDate, NumberOfDays+1, #duration(1,0,0,0)),
				    #"Converted to Table" = Table.FromList(Dates, Splitter.SplitByNothing(), null, null, ExtraValues.Error),
				    #"Renamed Columns" = Table.RenameColumns(#"Converted to Table",{{"Column1", "Date"}}),
				    #"Changed Type" = Table.TransformColumnTypes(#"Renamed Columns",{{"Date", type date}}),
				    #"Inserted Year" = Table.AddColumn(#"Changed Type", "Year", each Date.Year([Date]), type number),
				    #"Inserted Month" = Table.AddColumn(#"Inserted Year", "Month", each Date.Month([Date]), type number),
				    #"Inserted Month Name" = Table.AddColumn(#"Inserted Month", "Month Name", each Date.MonthName([Date]), type text),
				    #"Added Month Short Name" = Table.AddColumn(#"Inserted Month Name", "Month Short Name", each Text.Start([Month Name], 3), type text),
				    #"Added Year-Month" = Table.AddColumn(#"Added Month Short Name", "Year-Month", each Text.From([Year]) & "-" & Text.PadStart(Text.From([Month]), 2, "0"), type text),
				    #"Added Year Month Id" = Table.AddColumn(#"Added Year-Month", "Year Month Id", each [Year] * 100 + [Month], type number),
				    #"Added Year-Mth" = Table.AddColumn(#"Added Year Month Id", "Year-Mth", each Text.From([Year]) & "-" & [Month Short Name], type text),
				    #"Inserted Quarter" = Table.AddColumn(#"Added Year-Mth", "Quarter", each Date.QuarterOfYear([Date]), type number),
				    #"Added Year-Quarter" = Table.AddColumn(#"Inserted Quarter", "Year-Quarter", each Text.From([Year]) & "-Q" & Text.From([Quarter]), type text),
				    #"Added Quarter-Year" = Table.AddColumn(#"Added Year-Quarter", "Quarter-Year", each "Q" & Text.From([Quarter]) & " " & Text.From([Year]), type text),
				    #"Inserted Week of Year" = Table.AddColumn(#"Added Quarter-Year", "Week of Year", each Date.WeekOfYear([Date]), type number),
				    #"Inserted Week of Month" = Table.AddColumn(#"Inserted Week of Year", "Week of Month", each Date.WeekOfMonth([Date]), type number),
				    
				    // Add Week Start Date (standard week start - Sunday)
				    #"Added Week Start Date" = Table.AddColumn(#"Inserted Week of Month", "Week Start Date", each 
				        Date.AddDays([Date], -(Date.DayOfWeek([Date]))), 
				    type date),
				    
				    // Add Week End Date (standard week end - Saturday)
				    #"Added Week End Date" = Table.AddColumn(#"Added Week Start Date", "Week End Date", each 
				        Date.AddDays([Week Start Date], 6), 
				    type date),
				    
				    // Add Calendar Week Start Date (custom logic for month boundaries)
				    #"Added Calendar Week Start Date" = Table.AddColumn(#"Added Week End Date", "Calendar Week Start Date", each
				        let
				            StandardWeekStart = Date.AddDays([Date], -(Date.DayOfWeek([Date]))),
				            WeekStartMonth = Date.Month(StandardWeekStart),
				            CurrentMonth = Date.Month([Date])
				        in
				            if WeekStartMonth <> CurrentMonth then
				                // If week start is in different month, use first day of current month
				                Date.StartOfMonth([Date])
				            else
				                // Otherwise use standard week start
				                StandardWeekStart,
				    type date),
				    
				    #"Inserted Day" = Table.AddColumn(#"Added Calendar Week Start Date", "Day", each Date.Day([Date]), type number),
				    #"Inserted Day of Week" = Table.AddColumn(#"Inserted Day", "Day of Week", each Date.DayOfWeek([Date])+1, type number),
				    #"Inserted Day of Year" = Table.AddColumn(#"Inserted Day of Week", "Day of Year", each Date.DayOfYear([Date]), type number),
				    #"Inserted Day Name" = Table.AddColumn(#"Inserted Day of Year", "Day Name", each Date.DayOfWeekName([Date]), type text),
				    #"Added Day Short Name" = Table.AddColumn(#"Inserted Day Name", "Day Short Name", each Text.Start([Day Name], 3), type text),
				    #"Added Custom" = Table.AddColumn(#"Added Day Short Name", "Date Id", each Number.FromText(Date.ToText([Date], "yyyyMMdd"))),
				    
				    // Add Index Columns
				    #"Added Day Index" = Table.AddColumn(#"Added Custom", "Day Index", each Duration.Days([Date] - StartDate) + 1, type number),
				    
				    #"Added Month Index" = Table.AddColumn(#"Added Day Index", "Month Index", each 
				        ([Year] - Date.Year(StartDate)) * 12 + [Month] - Date.Month(StartDate) + 1, 
				    type number),
				    
				    #"Added Week Index" = Table.AddColumn(#"Added Month Index", "Week Index", each 
				        Duration.Days([Week Start Date] - Date.AddDays(StartDate, -(Date.DayOfWeek(StartDate)))) / 7 + 1,
				    type number),
				    
				    #"Added Quarter Index" = Table.AddColumn(#"Added Week Index", "Quarter Index", each 
				        ([Year] - Date.Year(StartDate)) * 4 + [Quarter] - Date.QuarterOfYear(StartDate) + 1,
				    type number),
				    
				    #"Added Is Month to Date" = Table.AddColumn(#"Added Quarter Index", "Is Month to Date", each 
				        Date.Year([Date]) = Date.Year(CurrentDate) and 
				        Date.Month([Date]) = Date.Month(CurrentDate) and 
				        [Date] <= CurrentDate, 
				    type logical),
				    #"Added Is Weekend" = Table.AddColumn(#"Added Is Month to Date", "Is Weekend", each if [Day of Week] = 1 then true
				else if [Day of Week] = 7 then true
				else false),
				    #"Changed Type1" = Table.TransformColumnTypes(#"Added Is Weekend",{{"Is Weekend", type logical}}),
				    #"Added Is Current Month" = Table.AddColumn(#"Changed Type1", "Is Current Month", each 
				        Date.Year([Date]) = Date.Year(CurrentDate) and 
				        Date.Month([Date]) = Date.Month(CurrentDate),
				    type logical),
				    #"Added Is Current Quarter" = Table.AddColumn(#"Added Is Current Month", "Is Current Quarter", each 
				        Date.Year([Date]) = Date.Year(CurrentDate) and 
				        [Quarter] = Date.QuarterOfYear(CurrentDate),
				    type logical),
				    #"Added Is Before Current Month" = Table.AddColumn(#"Added Is Current Quarter", "Is Before Current Month", each 
				        [Date] < Date.StartOfMonth(CurrentDate),
				    type logical),
				    #"Reordered Columns" = Table.ReorderColumns(#"Added Is Before Current Month",{
				        "Date Id", "Date", 
				        "Day Index", "Year", "Month Index", "Month", "Month Name", "Month Short Name", "Year Month Id", "Year-Month", "Year-Mth", 
				        "Quarter Index", "Quarter", "Year-Quarter", "Quarter-Year", 
				        "Week Index", "Week of Year", "Week of Month", 
				        "Week Start Date", "Week End Date", "Calendar Week Start Date",
				        "Day", "Day of Week", "Day Name", 
				        "Day Short Name", "Day of Year", "Is Month to Date", "Is Weekend", 
				        "Is Current Month", "Is Current Quarter", "Is Before Current Month"
				    }),
				    #"Renamed Columns1" = Table.RenameColumns(#"Reordered Columns",{{"Year-Month", "Year-Month Number"}}),
				    #"Sorted Rows" = Table.Sort(#"Renamed Columns1",{{"Date", Order.Ascending}}),
				    
				    //create new columns from meta table
				    #"Added Is Refresh Date" = Table.AddColumn(#"Sorted Rows", "Is Refresh Date", each [Date] = #"Get Refresh Thru Date", type logical),
				    #"Added Is Future Date" = Table.AddColumn(#"Added Is Refresh Date", "Is Future Date", each [Date] > #"Get Refresh Thru Date", type logical)
				in
				    #"Added Is Future Date"
				```

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

